package project.pkg3;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class InsertPlayerGUI extends javax.swing.JFrame
{

    PickCardsGUI parent;

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: InsertCustomerGUI
     * @Title: Default Constructor
     *
     * @Description: Sets the Customer Input GUI
     *
     * @Input: n/a
     * @Output: New form
     *
     * @Parameters: n/a
     * @Return: n/a
     *
     * @CalledBy: menuAddCustomer
     * @Calls: initComponents
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public InsertPlayerGUI(PickCardsGUI parent)
    {
        this.parent = parent;
        initComponents();
        this.setLocationRelativeTo(null);
        //set default button
        this.getRootPane().setDefaultButton(saveJButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src//CardImages//b1fh.png"));
        parent.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bgJPanel1 = new javax.swing.JPanel();
        lNameJTextField = new javax.swing.JTextField();
        fNameJTextField = new javax.swing.JTextField();
        lNameJLabel = new javax.swing.JLabel();
        fNameJLabel = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        custJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        saveJMenuItem = new javax.swing.JMenuItem();
        printJMenuItem = new javax.swing.JMenuItem();
        clearJMenuItem = new javax.swing.JMenuItem();
        quitJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Input");
        setAlwaysOnTop(true);
        setResizable(false);

        bgJPanel1.setBackground(new java.awt.Color(153, 204, 255));

        lNameJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lNameJTextField.setToolTipText("Customer's Last Name");

        fNameJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fNameJTextField.setToolTipText("Customer's First Name");

        lNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNameJLabel.setText("Last Name:");
        lNameJLabel.setToolTipText("Customer's Last Name");

        fNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fNameJLabel.setText("First Name:");
        fNameJLabel.setToolTipText("Customer's First Name");

        saveJButton.setBackground(new java.awt.Color(153, 204, 255));
        saveJButton.setMnemonic('S');
        saveJButton.setText("Save");
        saveJButton.setToolTipText("Saves the customer");
        saveJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveJButtonActionPerformed(evt);
            }
        });

        printJButton.setBackground(new java.awt.Color(153, 204, 255));
        printJButton.setMnemonic('P');
        printJButton.setText("Print");
        printJButton.setToolTipText("Prints the customer information");
        printJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printJButtonActionPerformed(evt);
            }
        });

        clearJButton.setBackground(new java.awt.Color(153, 204, 255));
        clearJButton.setMnemonic('C');
        clearJButton.setText("Clear");
        clearJButton.setToolTipText("Resets the form");
        clearJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearJButtonActionPerformed(evt);
            }
        });

        quitJButton.setBackground(new java.awt.Color(153, 204, 255));
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.setToolTipText("Closes this window without saving");
        quitJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgJPanel1Layout = new javax.swing.GroupLayout(bgJPanel1);
        bgJPanel1.setLayout(bgJPanel1Layout);
        bgJPanel1Layout.setHorizontalGroup(
            bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanel1Layout.createSequentialGroup()
                .addGroup(bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgJPanel1Layout.createSequentialGroup()
                        .addGroup(bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameJTextField)
                            .addComponent(lNameJTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgJPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitJButton)))
                .addContainerGap())
        );
        bgJPanel1Layout.setVerticalGroup(
            bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameJLabel)
                    .addComponent(fNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameJLabel)
                    .addComponent(lNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearJButton)
                    .addComponent(saveJButton)
                    .addComponent(printJButton)
                    .addComponent(quitJButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fileJMenu.setMnemonic('F');
        fileJMenu.setText("File");
        fileJMenu.setToolTipText("Additional Options");

        saveJMenuItem.setMnemonic('v');
        saveJMenuItem.setText("Save");
        saveJMenuItem.setToolTipText("Saves the customer");
        saveJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(saveJMenuItem);

        printJMenuItem.setMnemonic('r');
        printJMenuItem.setText("Print");
        printJMenuItem.setToolTipText("Prints this entire window");
        printJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(printJMenuItem);

        clearJMenuItem.setMnemonic('l');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.setToolTipText("Resets the form");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearJMenuItem);

        quitJMenuItem.setMnemonic('u');
        quitJMenuItem.setText("Quit");
        quitJMenuItem.setToolTipText("Closes this window without saving");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(quitJMenuItem);

        custJMenuBar.add(fileJMenu);

        setJMenuBar(custJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: quitJButtonActionPerformed
     * @Title: btnQuit
     *
     * @Description: Closes the form
     *
     * @Input: n/a
     * @Output: n/a
     *
     * @Parameters: java.awt.event.ActionEvent evt - Action
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls: n/a
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitJButtonActionPerformed
    {//GEN-HEADEREND:event_quitJButtonActionPerformed
        dispose();
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: quitJMenuItemActionPerformed
     * @Title: menuQuit
     *
     * @Description: Closes the form
     *
     * @Input: n/a
     * @Output: n/a
     *
     * @Parameters: java.awt.event.ActionEvent evt - Action
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls: n/a
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitJMenuItemActionPerformed
    {//GEN-HEADEREND:event_quitJMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_quitJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: printJButtonActionPerformed
     * @Title: btnPrint
     *
     * @Description: Prints the form
     *
     * @Input: n/a
     * @Output: Printer
     *
     * @Parameters: java.awt.event.ActionEvent evt - Action
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls: PrintUtilities.printComponent
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void printJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printJButtonActionPerformed
    {//GEN-HEADEREND:event_printJButtonActionPerformed
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: printJMenuItemActionPerformed
     * @Title: menuPrint
     *
     * @Description: Prints the form
     *
     * @Input: n/a
     * @Output: Printer
     *
     * @Parameters: java.awt.event.ActionEvent evt - Action
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls: PrintUtilities.printComponent
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void printJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printJMenuItemActionPerformed
    {//GEN-HEADEREND:event_printJMenuItemActionPerformed
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: clearJButtonActionPerformed
     * @Title: btnClear
     *
     * @Description:Clears the form
     *
     * @Input: java.awt.event.ActionEvent evt - Action
     * @Output: n/a
     *
     * @Parameters: n/a
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls:clear()
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearJButtonActionPerformed
    {//GEN-HEADEREND:event_clearJButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: clearJMenuItemActionPerformed
     * @Title: menuClear
     *
     * @Description: Clears the form
     *
     * @Input: n/a
     * @Output: n/a
     *
     * @Parameters: java.awt.event.ActionEvent evt - Action
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls: clear()
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearJMenuItemActionPerformed
    {//GEN-HEADEREND:event_clearJMenuItemActionPerformed
        clear();
    }//GEN-LAST:event_clearJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: saveJButtonActionPerformed
     * @Title: btnSave
     *
     * @Description: Saves the customer info
     *
     * @Input: n/a
     * @Output: n/a
     *
     * @Parameters: java.awt.event.ActionEvent evt - Action
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls: save()
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveJButtonActionPerformed
    {//GEN-HEADEREND:event_saveJButtonActionPerformed
        save();
    }//GEN-LAST:event_saveJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: saveJMenuItemActionPerformed
     * @Title: menuSave
     *
     * @Description: Saves the customer info
     *
     * @Input: n/a
     * @Output: n/a
     *
     * @Parameters: java.awt.event.ActionEvent evt - Action
     * @Return: n/a
     *
     * @CalledBy: n/a
     * @Calls: save()
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void saveJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveJMenuItemActionPerformed
    {//GEN-HEADEREND:event_saveJMenuItemActionPerformed
        save();
    }//GEN-LAST:event_saveJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: clear
     * @Title: Clear
     *
     * @Description: Clears both text boxes
     *
     * @Input: n/a
     * @Output:
     * <br>fNameJTextField - Clears
     * <br>lNameJTextField - Clears
     *
     * @Parameters: n/a
     * @Return: n/a
     *
     * @CalledBy: btnClear, menuClear
     * @Calls: n/a
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void clear()
    {
        fNameJTextField.setText("");
        lNameJTextField.setText("");
        fNameJTextField.requestFocus();
    }

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: InsertCustomerGUI
     * @File: InsertCustomerGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: save
     * @Title: Save
     *
     * @Description: Clears both text boxes
     *
     * @Input:
     * <br>fNameJTextField - Puts into string
     * <br>lNameJTextField - Puts into string
     *
     * @Output:
     * <br>Customer.txt
     *
     * @Parameters: n/a
     * @Return: n/a
     *
     * @CalledBy: btnSave, menuSave
     * @Calls: n/a
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 2/18/2016
     * @version 1.0
     * @HistoryLog: 2/18/16 - Built function and called methods
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void save()
    {
        try
        {
            //Verifies inputs are valid
            if (!fNameJTextField.getText().isEmpty())
            {
                if (!lNameJTextField.getText().isEmpty())
                {
                    String playerName = fNameJTextField.getText() + " "
                            + lNameJTextField.getText();
                    //Places the data in the file, closes file and window
                    if (DataManager.savePlayer(playerName))
                    {
                        new PickCardsGUI().setVisible(true);
                        dispose();
                    }
                } else
                {
                    lNameJTextField.requestFocus();
                    throw new IllegalStateException();
                }
            } else
            {
                fNameJTextField.requestFocus();
                throw new IllegalStateException();
            }
        } catch (IllegalStateException exp)// catch empy text field
        {
            JOptionPane.showMessageDialog(null, "Please enter a first AND last name.", "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InsertPlayerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InsertPlayerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InsertPlayerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InsertPlayerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new InsertPlayerGUI(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgJPanel1;
    private javax.swing.JButton clearJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JMenuBar custJMenuBar;
    private javax.swing.JLabel fNameJLabel;
    private javax.swing.JTextField fNameJTextField;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JLabel lNameJLabel;
    private javax.swing.JTextField lNameJTextField;
    private javax.swing.JButton printJButton;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JButton quitJButton;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JButton saveJButton;
    private javax.swing.JMenuItem saveJMenuItem;
    // End of variables declaration//GEN-END:variables
}
