/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg3;

import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Kevin
 */
public class PickCardsGUI extends javax.swing.JFrame
{

    final short PAIR = 2;

    /**
     * Creates new form PickCardsGUI
     */
    public PickCardsGUI()
    {
        initComponents();

        this.setLocationRelativeTo(null);
        //set default button
        this.getRootPane().setDefaultButton(goJButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src//CardImages//b2fh.png"));
        saveJButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        modeJbuttonGroup = new javax.swing.ButtonGroup();
        bgJPanel = new javax.swing.JPanel();
        cardGroupJPanel = new javax.swing.JPanel();
        card1JLabel = new javax.swing.JLabel();
        card2JLabel = new javax.swing.JLabel();
        card3JLabel = new javax.swing.JLabel();
        card4JLabel = new javax.swing.JLabel();
        dataJLabel = new javax.swing.JLabel();
        drawsJLabel = new javax.swing.JLabel();
        controlsJPanel = new javax.swing.JPanel();
        goJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        homeJButton = new javax.swing.JButton();
        mainJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        saveJMenuItem = new javax.swing.JMenuItem();
        printJMenuItem = new javax.swing.JMenuItem();
        fileJSeparator = new javax.swing.JPopupMenu.Separator();
        quitJMenuItem = new javax.swing.JMenuItem();
        actionsJMenu = new javax.swing.JMenu();
        goJMenuItem = new javax.swing.JMenuItem();
        actions_topJSeparator = new javax.swing.JPopupMenu.Separator();
        logJMenuItem = new javax.swing.JMenuItem();
        statsJMenuItem = new javax.swing.JMenuItem();
        printStatsJMenuItem = new javax.swing.JMenuItem();
        actions_bottomJSeparator = new javax.swing.JPopupMenu.Separator();
        clearJMenuItem = new javax.swing.JMenuItem();
        settingsJMenu = new javax.swing.JMenu();
        removeJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        keepJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        helpJMenu = new javax.swing.JMenu();
        instructionsJMenuItem = new javax.swing.JMenuItem();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cards Collection");
        setResizable(false);

        bgJPanel.setBackground(new java.awt.Color(0, 0, 0));

        cardGroupJPanel.setBackground(new java.awt.Color(0, 0, 0));
        cardGroupJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Successful Cards:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 0, 51))); // NOI18N
        cardGroupJPanel.setForeground(new java.awt.Color(255, 0, 51));

        card1JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card1JLabel.setText("jLabel1");

        card2JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card2JLabel.setText("jLabel1");

        card3JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card3JLabel.setText("jLabel1");

        card4JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card4JLabel.setText("jLabel1");

        javax.swing.GroupLayout cardGroupJPanelLayout = new javax.swing.GroupLayout(cardGroupJPanel);
        cardGroupJPanel.setLayout(cardGroupJPanelLayout);
        cardGroupJPanelLayout.setHorizontalGroup(
            cardGroupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGroupJPanelLayout.createSequentialGroup()
                .addComponent(card1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(card2JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(card3JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(card4JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cardGroupJPanelLayout.setVerticalGroup(
            cardGroupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGroupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(card1JLabel)
                .addComponent(card4JLabel)
                .addComponent(card2JLabel)
                .addComponent(card3JLabel))
        );

        dataJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dataJLabel.setForeground(new java.awt.Color(255, 51, 51));
        dataJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataJLabel.setText("Number Of Picks:");
        dataJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        drawsJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        drawsJLabel.setForeground(new java.awt.Color(255, 51, 51));
        drawsJLabel.setText("0");
        drawsJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        controlsJPanel.setBackground(new java.awt.Color(0, 0, 0));
        controlsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(251, 0, 51))); // NOI18N

        goJButton.setBackground(new java.awt.Color(255, 0, 51));
        goJButton.setText("Go");
        goJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                goJButtonActionPerformed(evt);
            }
        });

        printJButton.setBackground(new java.awt.Color(255, 0, 51));
        printJButton.setText("Print");
        printJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printJButtonActionPerformed(evt);
            }
        });

        saveJButton.setBackground(new java.awt.Color(255, 0, 51));
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveJButtonActionPerformed(evt);
            }
        });

        homeJButton.setBackground(new java.awt.Color(255, 0, 51));
        homeJButton.setText("Quit");
        homeJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                homeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlsJPanelLayout = new javax.swing.GroupLayout(controlsJPanel);
        controlsJPanel.setLayout(controlsJPanelLayout);
        controlsJPanelLayout.setHorizontalGroup(
            controlsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsJPanelLayout.createSequentialGroup()
                .addComponent(goJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(printJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        controlsJPanelLayout.setVerticalGroup(
            controlsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(goJButton)
                .addComponent(printJButton)
                .addComponent(saveJButton)
                .addComponent(homeJButton))
        );

        javax.swing.GroupLayout bgJPanelLayout = new javax.swing.GroupLayout(bgJPanel);
        bgJPanel.setLayout(bgJPanelLayout);
        bgJPanelLayout.setHorizontalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardGroupJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgJPanelLayout.createSequentialGroup()
                        .addComponent(dataJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drawsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controlsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgJPanelLayout.setVerticalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardGroupJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataJLabel)
                    .addComponent(drawsJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileJMenu.setText("File");

        saveJMenuItem.setText("Save");
        fileJMenu.add(saveJMenuItem);

        printJMenuItem.setText("Print");
        printJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(printJMenuItem);
        fileJMenu.add(fileJSeparator);

        quitJMenuItem.setText("Quit");
        fileJMenu.add(quitJMenuItem);

        mainJMenuBar.add(fileJMenu);

        actionsJMenu.setText("Actions");

        goJMenuItem.setText("Go");
        actionsJMenu.add(goJMenuItem);
        actionsJMenu.add(actions_topJSeparator);

        logJMenuItem.setText("View Log");
        actionsJMenu.add(logJMenuItem);

        statsJMenuItem.setText("See Stats");
        statsJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                statsJMenuItemActionPerformed(evt);
            }
        });
        actionsJMenu.add(statsJMenuItem);

        printStatsJMenuItem.setText("Print Stats");
        actionsJMenu.add(printStatsJMenuItem);
        actionsJMenu.add(actions_bottomJSeparator);

        clearJMenuItem.setText("Clear Stats");
        actionsJMenu.add(clearJMenuItem);

        mainJMenuBar.add(actionsJMenu);

        settingsJMenu.setText("Settings");

        removeJRadioButtonMenuItem.setSelected(true);
        removeJRadioButtonMenuItem.setText("Remove Card");
        settingsJMenu.add(removeJRadioButtonMenuItem);

        keepJRadioButtonMenuItem.setSelected(true);
        keepJRadioButtonMenuItem.setText("Keep Card");
        settingsJMenu.add(keepJRadioButtonMenuItem);

        mainJMenuBar.add(settingsJMenu);

        helpJMenu.setText("Help");

        instructionsJMenuItem.setText("Instructions");
        instructionsJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                instructionsJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(instructionsJMenuItem);

        aboutJMenuItem.setText("About");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        mainJMenuBar.add(helpJMenu);

        setJMenuBar(mainJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_homeJButtonActionPerformed
    {//GEN-HEADEREND:event_homeJButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void goJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_goJButtonActionPerformed
    {//GEN-HEADEREND:event_goJButtonActionPerformed
        final String FILEPATH = "src//CardImages//";
        final String EXTENSION = ".png";

        DeckOfCards.reset();

        String cards[] = DeckOfCards.getSet();

        card1JLabel.setIcon(new ImageIcon(FILEPATH + cards[0] + EXTENSION));
        card2JLabel.setIcon(new ImageIcon(FILEPATH + cards[1] + EXTENSION));
        card3JLabel.setIcon(new ImageIcon(FILEPATH + cards[2] + EXTENSION));
        card4JLabel.setIcon(new ImageIcon(FILEPATH + cards[3] + EXTENSION));

        drawsJLabel.setText(Integer.toString(DeckOfCards.draws));
        saveJButton.setEnabled(true);
    }//GEN-LAST:event_goJButtonActionPerformed

    private void instructionsJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_instructionsJMenuItemActionPerformed
    {//GEN-HEADEREND:event_instructionsJMenuItemActionPerformed
        //DataManager.helpMenu("Instructions");
        DataManager.infoPop(instructionsJMenuItem.getText());
    }//GEN-LAST:event_instructionsJMenuItemActionPerformed

    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutJMenuItemActionPerformed
    {//GEN-HEADEREND:event_aboutJMenuItemActionPerformed
        DataManager.infoPop(aboutJMenuItem.getText());
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveJButtonActionPerformed
    {//GEN-HEADEREND:event_saveJButtonActionPerformed
        DataManager.save(drawsJLabel.getText());
        saveJButton.setEnabled(false);
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void statsJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_statsJMenuItemActionPerformed
    {//GEN-HEADEREND:event_statsJMenuItemActionPerformed
        DataManager.stats();
    }//GEN-LAST:event_statsJMenuItemActionPerformed

    private void printJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printJButtonActionPerformed
    {//GEN-HEADEREND:event_printJButtonActionPerformed
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJButtonActionPerformed

    private void printJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printJMenuItemActionPerformed
    {//GEN-HEADEREND:event_printJMenuItemActionPerformed
        PrintUtilities.printComponent(cardGroupJPanel);
    }//GEN-LAST:event_printJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PickCardsGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JMenu actionsJMenu;
    private javax.swing.JPopupMenu.Separator actions_bottomJSeparator;
    private javax.swing.JPopupMenu.Separator actions_topJSeparator;
    private javax.swing.JPanel bgJPanel;
    private javax.swing.JLabel card1JLabel;
    private javax.swing.JLabel card2JLabel;
    private javax.swing.JLabel card3JLabel;
    private javax.swing.JLabel card4JLabel;
    private javax.swing.JPanel cardGroupJPanel;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JPanel controlsJPanel;
    private javax.swing.JLabel dataJLabel;
    private javax.swing.JLabel drawsJLabel;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JPopupMenu.Separator fileJSeparator;
    private javax.swing.JButton goJButton;
    private javax.swing.JMenuItem goJMenuItem;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JButton homeJButton;
    private javax.swing.JMenuItem instructionsJMenuItem;
    private javax.swing.JRadioButtonMenuItem keepJRadioButtonMenuItem;
    private javax.swing.JMenuItem logJMenuItem;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.ButtonGroup modeJbuttonGroup;
    private javax.swing.JButton printJButton;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JMenuItem printStatsJMenuItem;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JRadioButtonMenuItem removeJRadioButtonMenuItem;
    private javax.swing.JButton saveJButton;
    private javax.swing.JMenuItem saveJMenuItem;
    private javax.swing.JMenu settingsJMenu;
    private javax.swing.JMenuItem statsJMenuItem;
    // End of variables declaration//GEN-END:variables
}
