/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg3;

import java.awt.Toolkit;

/**
 *
 * @author Kevin
 */
public class PickCardsGUI extends javax.swing.JFrame
{

    /**
     * Creates new form PickCardsGUI
     */
    public PickCardsGUI()
    {
        initComponents();
         this.setLocationRelativeTo(null);
        //set default button
        this.getRootPane().setDefaultButton(goJButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("CardImages//54.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        bgJPanel = new javax.swing.JPanel();
        cardGroupJPanel1 = new javax.swing.JPanel();
        card1JLabel = new javax.swing.JLabel();
        card2JLabel = new javax.swing.JLabel();
        card3JLabel = new javax.swing.JLabel();
        card4JLabel = new javax.swing.JLabel();
        dataJLabel = new javax.swing.JLabel();
        picksJLabel = new javax.swing.JLabel();
        controlsJPanel = new javax.swing.JPanel();
        goJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        homeJButton = new javax.swing.JButton();
        mainJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        actionsJMenu = new javax.swing.JMenu();
        settingsJMenu = new javax.swing.JMenu();
        helpJMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cards Collection");
        setResizable(false);

        bgJPanel.setBackground(new java.awt.Color(0, 0, 0));

        cardGroupJPanel1.setBackground(new java.awt.Color(0, 0, 0));
        cardGroupJPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Successful Cards:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 0, 51))); // NOI18N
        cardGroupJPanel1.setForeground(new java.awt.Color(255, 0, 51));

        card1JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card1JLabel.setText("jLabel1");

        card2JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card2JLabel.setText("jLabel1");

        card3JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card3JLabel.setText("jLabel1");

        card4JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CardImages/b2fv.png"))); // NOI18N
        card4JLabel.setText("jLabel1");

        javax.swing.GroupLayout cardGroupJPanel1Layout = new javax.swing.GroupLayout(cardGroupJPanel1);
        cardGroupJPanel1.setLayout(cardGroupJPanel1Layout);
        cardGroupJPanel1Layout.setHorizontalGroup(
            cardGroupJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGroupJPanel1Layout.createSequentialGroup()
                .addComponent(card1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(card2JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(card3JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(card4JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cardGroupJPanel1Layout.setVerticalGroup(
            cardGroupJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGroupJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(card1JLabel)
                .addComponent(card4JLabel)
                .addComponent(card2JLabel)
                .addComponent(card3JLabel))
        );

        dataJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dataJLabel.setForeground(new java.awt.Color(255, 51, 51));
        dataJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataJLabel.setText("Number Of Picks:");
        dataJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        picksJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        picksJLabel.setForeground(new java.awt.Color(255, 51, 51));
        picksJLabel.setText("7");
        picksJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        controlsJPanel.setBackground(new java.awt.Color(0, 0, 0));
        controlsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(251, 0, 51))); // NOI18N

        goJButton.setBackground(new java.awt.Color(255, 0, 51));
        goJButton.setText("Go");

        printJButton.setBackground(new java.awt.Color(255, 0, 51));
        printJButton.setText("Print");

        saveJButton.setBackground(new java.awt.Color(255, 0, 51));
        saveJButton.setText("Save");

        homeJButton.setBackground(new java.awt.Color(255, 0, 51));
        homeJButton.setText("Quit");

        javax.swing.GroupLayout controlsJPanelLayout = new javax.swing.GroupLayout(controlsJPanel);
        controlsJPanel.setLayout(controlsJPanelLayout);
        controlsJPanelLayout.setHorizontalGroup(
            controlsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsJPanelLayout.createSequentialGroup()
                .addComponent(goJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(printJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        controlsJPanelLayout.setVerticalGroup(
            controlsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(goJButton)
                .addComponent(printJButton)
                .addComponent(saveJButton)
                .addComponent(homeJButton))
        );

        javax.swing.GroupLayout bgJPanelLayout = new javax.swing.GroupLayout(bgJPanel);
        bgJPanel.setLayout(bgJPanelLayout);
        bgJPanelLayout.setHorizontalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardGroupJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgJPanelLayout.createSequentialGroup()
                        .addComponent(dataJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(picksJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controlsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgJPanelLayout.setVerticalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardGroupJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataJLabel)
                    .addComponent(picksJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileJMenu.setText("File");
        mainJMenuBar.add(fileJMenu);

        actionsJMenu.setText("Actions");
        mainJMenuBar.add(actionsJMenu);

        settingsJMenu.setText("Settings");
        mainJMenuBar.add(settingsJMenu);

        helpJMenu.setText("Help");

        jMenuItem1.setText("jMenuItem1");
        helpJMenu.add(jMenuItem1);

        mainJMenuBar.add(helpJMenu);

        setJMenuBar(mainJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PickCardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PickCardsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionsJMenu;
    private javax.swing.JPanel bgJPanel;
    private javax.swing.JLabel card1JLabel;
    private javax.swing.JLabel card2JLabel;
    private javax.swing.JLabel card3JLabel;
    private javax.swing.JLabel card4JLabel;
    private javax.swing.JPanel cardGroupJPanel1;
    private javax.swing.JPanel controlsJPanel;
    private javax.swing.JLabel dataJLabel;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JButton goJButton;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JButton homeJButton;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.JLabel picksJLabel;
    private javax.swing.JButton printJButton;
    private javax.swing.JButton saveJButton;
    private javax.swing.JMenu settingsJMenu;
    // End of variables declaration//GEN-END:variables
}
