/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.crdpk;

/**
 *
 * @author Kevin
 */
public class PrintStatsGUI extends javax.swing.JFrame
{

    /**
     * Creates new form PrintStatsGUI
     */
    public PrintStatsGUI()
    {
        initComponents();
    }

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *
     * @Class: PrintStatsGUI
     * @File: PrintStatsGUI.java
     *
     * @author: Kevin Manning
     *
     * @Function: PrintStatsGUI
     * @Title: Overloaded Constructor
     *
     * @Description: Overloaded constructor to create temporary window for
     * printing
     *
     * @Input: n/a
     * @Output: Print
     * @Parameters:
     * <br>int index - Location in a list the required player is placed
     * <br>boolean remove - Determines which version of game is being played for
     * stats display
     *
     * @Return: n/a
     *
     * @CalledBy: DeckOfCards.printStatsJMenuItem
     * @Calls:
     * <br>Player.getName; retrieves the player's name as a string
     * <br>Player.getStats; retrieves the player's statistics as a string
     * <br>Player.getLogs; retrieves the player's log of games as a string
     * <br>PrintUtilities.printComponent; Prints the text pane
     *
     * @Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
     * @Date: 3/9/2016
     * @version 1.0
     * @HistoryLog: 3/9/16 - Interface and Methods created
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public PrintStatsGUI(int index, boolean remove)
    {
        //Establishes the singleton player to pass values
        Player player = Player.getPlayer();
        //creates the form
        initComponents();
        //centers the form
        this.setLocationRelativeTo(null);
        //Fills the pane with data
        statsJTextPane.setText(player.getName(index) + "'s Stats:\n"
                + player.getStats(index, remove) + "\n\nLog of games played:\n"
                + player.getLogs(index, remove));
        //prints the pane
        PrintUtilities.printComponent(statsJTextPane);
        //Closes this window when completed
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        statsJScrollPane = new javax.swing.JScrollPane();
        statsJTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print");
        setResizable(false);

        statsJScrollPane.setViewportView(statsJTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statsJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PrintStatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PrintStatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PrintStatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PrintStatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PrintStatsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane statsJScrollPane;
    private javax.swing.JTextPane statsJTextPane;
    // End of variables declaration//GEN-END:variables
}
