/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import java.text.DecimalFormat;

/**
 *
 * @author Kevin
 */
public class OhmsLaw extends javax.swing.JFrame
{

    /**
     * Creates new form OhmsLaw
     */
    public OhmsLaw()
    {
        initComponents();
        //set location of window
        this.setLocationRelativeTo(null);
        //set default button
        this.getRootPane().setDefaultButton(calculateJButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/OhmsFormula.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titleJLabel = new javax.swing.JLabel();
        vJLabel = new javax.swing.JLabel();
        voltsJTextField = new javax.swing.JTextField();
        voltsJLabel = new javax.swing.JLabel();
        rJLabel = new javax.swing.JLabel();
        resistanceJTextField = new javax.swing.JTextField();
        resistanceJLabel = new javax.swing.JLabel();
        iJLabel = new javax.swing.JLabel();
        currentJTextField = new javax.swing.JTextField();
        currentJLabel = new javax.swing.JLabel();
        controlJPanel = new javax.swing.JPanel();
        calculateJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ohm's Law");
        setResizable(false);

        titleJLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(153, 0, 0));
        titleJLabel.setLabelFor(titleJLabel);
        titleJLabel.setText("Ohm's Law");
        titleJLabel.setToolTipText("");

        vJLabel.setLabelFor(vJLabel);
        vJLabel.setText("V:");

        voltsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        voltsJLabel.setText("volts");

        rJLabel.setLabelFor(vJLabel);
        rJLabel.setText("R:");

        resistanceJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        resistanceJLabel.setText("ohms");

        iJLabel.setLabelFor(vJLabel);
        iJLabel.setText("I:");

        currentJTextField.setEditable(false);
        currentJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        currentJLabel.setText("amperes");

        controlJPanel.setLayout(new java.awt.GridLayout(2, 2));

        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate");
        calculateJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                calculateJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(calculateJButton);

        clearJButton.setMnemonic('l');
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(clearJButton);

        printJButton.setMnemonic('P');
        printJButton.setText("Print");
        printJButton.setEnabled(false);
        controlJPanel.add(printJButton);

        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(quitJButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(voltsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltsJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iJLabel)
                        .addGap(16, 16, 16)
                        .addComponent(currentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resistanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resistanceJLabel))
                    .addComponent(controlJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vJLabel)
                    .addComponent(voltsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltsJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rJLabel)
                    .addComponent(resistanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resistanceJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iJLabel)
                    .addComponent(currentJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(controlJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculateJButtonActionPerformed
    {//GEN-HEADEREND:event_calculateJButtonActionPerformed
        // Calculate the current given voltage and resistance
        DecimalFormat twoDecimals = new DecimalFormat("#,##0.00");
        float volts, resistance, current;
        volts = Float.parseFloat(voltsJTextField.getText());
        resistance = Float.parseFloat(resistanceJTextField.getText());
        current = volts / resistance;
        currentJTextField.setText(twoDecimals.format(current));
    }//GEN-LAST:event_calculateJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearJButtonActionPerformed
    {//GEN-HEADEREND:event_clearJButtonActionPerformed
        //Centers the form

        // Clear all text fields to reset the form
        voltsJTextField.setText("");
        resistanceJTextField.setText("");
        currentJTextField.setText("");
        voltsJTextField.requestFocus();
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitJButtonActionPerformed
    {//GEN-HEADEREND:event_quitJButtonActionPerformed
        // Terminate the application
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OhmsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OhmsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OhmsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OhmsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OhmsLaw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JLabel currentJLabel;
    private javax.swing.JTextField currentJTextField;
    private javax.swing.JLabel iJLabel;
    private javax.swing.JButton printJButton;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel rJLabel;
    private javax.swing.JLabel resistanceJLabel;
    private javax.swing.JTextField resistanceJTextField;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel vJLabel;
    private javax.swing.JLabel voltsJLabel;
    private javax.swing.JTextField voltsJTextField;
    // End of variables declaration//GEN-END:variables
}
