package Project1;

import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Class:
 * Project1 File: Project1.java Description: GUI interface for Annuity
 * calculator
 *
 * @author: Kevin Manning Environment: PC, Windows 10, jdk8.0, NetBeans 8.1
 * Date: 1/25/2016
 * @version 1.0 History Log: 1/25/16 - Interface and Methods created
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
public class Project1 extends javax.swing.JFrame
{

    /**
     * Creates new form GUIJFrame
     */
    public Project1()
    {
        initComponents();
        //set location of window
        this.setLocationRelativeTo(null);
        //set default button
        this.getRootPane().setDefaultButton(calcJButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(
                "src/Project1/house.png"));

        //Sets form to default values and sets focus
        callDefaults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        inputJPanel = new javax.swing.JPanel();
        paymentJLabel = new javax.swing.JLabel();
        paymentJTextField = new javax.swing.JTextField();
        rateJLabel = new javax.swing.JLabel();
        rateJSpinner = new javax.swing.JSpinner();
        nJLabel = new javax.swing.JLabel();
        nJTextField = new javax.swing.JTextField();
        yearsJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();
        imageJLabel = new javax.swing.JLabel();
        balanceJLabel = new javax.swing.JLabel();
        balanceJTextField = new javax.swing.JTextField();
        totalJLabel = new javax.swing.JLabel();
        totalJTextField = new javax.swing.JTextField();
        interestJLabel = new javax.swing.JLabel();
        interestJTextField = new javax.swing.JTextField();
        errorJLabel = new javax.swing.JLabel();
        calcJButton = new javax.swing.JButton();
        clrJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        mainJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        clearJMenuItem = new javax.swing.JMenuItem();
        printJMenuItem = new javax.swing.JMenuItem();
        closeJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        instJMenuItem = new javax.swing.JMenuItem();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project 1 (01/26/16)");
        setResizable(false);

        inputJPanel.setBackground(new java.awt.Color(102, 204, 255));

        paymentJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paymentJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentJLabel.setText("Periodic Payment:");

        rateJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rateJLabel.setText("Interest (as a %):");

        rateJSpinner.setModel(new javax.swing.SpinnerNumberModel(8.0d, 0.0d, 100.0d, 0.5d));

        nJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nJLabel.setText("Compounds per year:");

        yearsJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearsJLabel.setText("Years:");

        yearsJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yearsJTextFieldActionPerformed(evt);
            }
        });

        imageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/house.png"))); // NOI18N

        javax.swing.GroupLayout inputJPanelLayout = new javax.swing.GroupLayout(inputJPanel);
        inputJPanel.setLayout(inputJPanelLayout);
        inputJPanelLayout.setHorizontalGroup(
            inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(paymentJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rateJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearsJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        inputJPanelLayout.setVerticalGroup(
            inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imageJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inputJPanelLayout.createSequentialGroup()
                        .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentJLabel)
                            .addComponent(paymentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rateJLabel)
                            .addComponent(rateJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearsJLabel)
                            .addComponent(yearsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        balanceJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balanceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceJLabel.setText("Future Annuity Balance:");

        balanceJTextField.setEditable(false);
        balanceJTextField.setBackground(new java.awt.Color(255, 255, 255));
        balanceJTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        balanceJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                balanceJTextFieldActionPerformed(evt);
            }
        });

        totalJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalJLabel.setText("Total of Payments:");

        totalJTextField.setEditable(false);
        totalJTextField.setBackground(new java.awt.Color(255, 255, 255));
        totalJTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        interestJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        interestJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        interestJLabel.setText("Total of Interest Earned:");

        interestJTextField.setEditable(false);
        interestJTextField.setBackground(new java.awt.Color(255, 255, 255));
        interestJTextField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        errorJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorJLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorJLabel.setText(" ");

        calcJButton.setBackground(new java.awt.Color(102, 204, 255));
        calcJButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        calcJButton.setMnemonic('C');
        calcJButton.setText("Calculate");
        calcJButton.setToolTipText("Calculates Future Annuity");
        calcJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                calcJButtonActionPerformed(evt);
            }
        });

        clrJButton.setBackground(new java.awt.Color(102, 204, 255));
        clrJButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        clrJButton.setMnemonic('r');
        clrJButton.setText("Clear");
        clrJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clrJButtonActionPerformed(evt);
            }
        });

        printJButton.setBackground(new java.awt.Color(102, 204, 255));
        printJButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        printJButton.setMnemonic('P');
        printJButton.setText("Print");
        printJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printJButtonActionPerformed(evt);
            }
        });

        quitJButton.setBackground(new java.awt.Color(102, 204, 255));
        quitJButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitJButtonActionPerformed(evt);
            }
        });

        fileJMenu.setMnemonic('F');
        fileJMenu.setText("File");

        clearJMenuItem.setMnemonic('r');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearJMenuItem);

        printJMenuItem.setMnemonic('P');
        printJMenuItem.setText("Print");
        printJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(printJMenuItem);

        closeJMenuItem.setMnemonic('Q');
        closeJMenuItem.setText("Quit");
        closeJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(closeJMenuItem);

        mainJMenuBar.add(fileJMenu);

        helpJMenu.setMnemonic('H');
        helpJMenu.setText("Help");

        instJMenuItem.setMnemonic('I');
        instJMenuItem.setText("Instructions");
        instJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                instJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(instJMenuItem);

        aboutJMenuItem.setMnemonic('A');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        mainJMenuBar.add(helpJMenu);

        setJMenuBar(mainJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calcJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clrJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(balanceJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(interestJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalJTextField)
                                    .addComponent(interestJTextField)
                                    .addComponent(balanceJTextField))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceJLabel)
                    .addComponent(balanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interestJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestJLabel))
                .addGap(1, 1, 1)
                .addComponent(errorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clrJButton)
                    .addComponent(printJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearsJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yearsJTextFieldActionPerformed
    {//GEN-HEADEREND:event_yearsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsJTextFieldActionPerformed

    private void balanceJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_balanceJTextFieldActionPerformed
    {//GEN-HEADEREND:event_balanceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceJTextFieldActionPerformed

    private void calcJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calcJButtonActionPerformed
    {//GEN-HEADEREND:event_calcJButtonActionPerformed
        try
        {
            //Formatter for currency display
            DecimalFormat twoDecimal = new DecimalFormat("$#,##0.00");

            //Calculate the annuity through object
            AnnuityStorage annuity = new AnnuityStorage(
                    Double.parseDouble(paymentJTextField.getText()),
                    (Double) rateJSpinner.getValue(),
                    Integer.parseInt(nJTextField.getText()),
                    Integer.parseInt(yearsJTextField.getText())
            );

            //Verifies inputs for valitidity
            boolean invalidInputs = (annuity.getDblPayment() <= 0
                    || annuity.getDblPayment() > 1000000000
                    || annuity.getDblRate() < 0 || annuity.getDblRate() > 100
                    || annuity.getIntN() < 0 || annuity.getIntN() > 365
                    || annuity.getIntYears() < 0 || annuity.getIntYears() > 100);

            if (invalidInputs)
            {
                throw new NumberFormatException();
            }

            //Resets warning label if no exception is thrown
            errorJLabel.setText("");

            //Output
            balanceJTextField.setText(twoDecimal.format(annuity.getDblBalance()));
            interestJTextField.setText(twoDecimal.format(annuity.getDblInterest()));
            totalJTextField.setText(twoDecimal.format(annuity.getDblTotal()));

        } catch (NumberFormatException exp)
        {
            //Handles thrown exception
            errorJLabel.setText(
                    "Please enter a positive number for all required fields");

            paymentJTextField.requestFocus();
            paymentJTextField.selectAll();
        }
    }//GEN-LAST:event_calcJButtonActionPerformed

    private void clrJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clrJButtonActionPerformed
    {//GEN-HEADEREND:event_clrJButtonActionPerformed
        // Clear All Fields and Resets Form
        callDefaults();

    }//GEN-LAST:event_clrJButtonActionPerformed

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitJButtonActionPerformed
    {//GEN-HEADEREND:event_quitJButtonActionPerformed
        // End applicaiton
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearJMenuItemActionPerformed
    {//GEN-HEADEREND:event_clearJMenuItemActionPerformed
        // Clear All Fields and Resets Form
        callDefaults();
    }//GEN-LAST:event_clearJMenuItemActionPerformed

    private void closeJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeJMenuItemActionPerformed
    {//GEN-HEADEREND:event_closeJMenuItemActionPerformed
        // End applicaiton
        System.exit(0);
    }//GEN-LAST:event_closeJMenuItemActionPerformed

    private void printJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printJButtonActionPerformed
    {//GEN-HEADEREND:event_printJButtonActionPerformed
        //Prints the entire user interface
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJButtonActionPerformed

    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutJMenuItemActionPerformed
    {//GEN-HEADEREND:event_aboutJMenuItemActionPerformed
        //A message with generic information regarding the program
        JOptionPane.showMessageDialog(null,
                "The Future Annuitites Calculator (Project1) was created by "
                + "Kevin Manning in January, 2016,\nin accordance with guidelines"
                + " provided by Nico Cuvelski as part of the CS& 141 Course.\n\n"
                + "This Calculator is provided as-is, and makes no guarantees of"
                + " compatibility or functionality\noutside of the requirements "
                + "of the class.\n\n\n"
                + "For additional information regarding this software, please "
                + "visit the \"Instructions\" option in\nthe \"Help\" menu.",
                "About Project1",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    private void printJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printJMenuItemActionPerformed
    {//GEN-HEADEREND:event_printJMenuItemActionPerformed
        //Prints the entire user interface
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJMenuItemActionPerformed

    private void instJMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_instJMenuItemActionPerformed
    {//GEN-HEADEREND:event_instJMenuItemActionPerformed
        //Popup window for instuctions on using program        
        JOptionPane.showMessageDialog(null,
                "To use the program, please enter the following pieces of "
                        +"information into the provided fields:"
                        +"\n    Amount of Payments (Must be a positive number)."
                        +"\n    Interst rate (Spinner increments at half a percent;"
                        +" custom values are allowed)."
                        +"\n    Number of Compoundings per year (maximum of 365, "
                        +"which is daily value)."
                        +"\n    The Number of years you'll be investing for."
                        +"\n\nThen press the Calculate Button (or \"Enter\") to"
                        +" calculate final amounts.",
                "Instructions",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_instJMenuItemActionPerformed

    private void callDefaults()
    {
        //Clears and resets all fields to default values
        //Used on instantiation and when user calls clear function
        paymentJTextField.setText("");
        rateJSpinner.setValue(8.0);
        nJTextField.setText("2");
        yearsJTextField.setText("");
        errorJLabel.setText("");
        balanceJTextField.setText("$0.00");
        totalJTextField.setText("$0.00");
        interestJTextField.setText("$0.00");
        paymentJTextField.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Project1().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JLabel balanceJLabel;
    private javax.swing.JTextField balanceJTextField;
    private javax.swing.JButton calcJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JMenuItem closeJMenuItem;
    private javax.swing.JButton clrJButton;
    private javax.swing.JLabel errorJLabel;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JPanel inputJPanel;
    private javax.swing.JMenuItem instJMenuItem;
    private javax.swing.JLabel interestJLabel;
    private javax.swing.JTextField interestJTextField;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.JLabel nJLabel;
    private javax.swing.JTextField nJTextField;
    private javax.swing.JLabel paymentJLabel;
    private javax.swing.JTextField paymentJTextField;
    private javax.swing.JButton printJButton;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel rateJLabel;
    private javax.swing.JSpinner rateJSpinner;
    private javax.swing.JLabel totalJLabel;
    private javax.swing.JTextField totalJTextField;
    private javax.swing.JLabel yearsJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
}
