package Lab2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kevin
 */
public class LoanGUI extends javax.swing.JFrame
{

    /**
     * Creates new form LoanGUI
     */
    public LoanGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        counterJLabel = new javax.swing.JLabel();
        counterJTextField = new javax.swing.JTextField();
        amountJLabel = new javax.swing.JLabel();
        amountJTextField = new javax.swing.JTextField();
        rateJLabel = new javax.swing.JLabel();
        rateJTextField = new javax.swing.JTextField();
        yearsJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 5, 5));

        counterJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        counterJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        counterJLabel.setText("Calculation Counter");
        getContentPane().add(counterJLabel);

        counterJTextField.setEditable(false);
        counterJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        counterJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        counterJTextField.setText("6");
        counterJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                counterJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(counterJTextField);

        amountJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amountJLabel.setText("Loan Amount");
        getContentPane().add(amountJLabel);

        amountJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amountJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                amountJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(amountJTextField);

        rateJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rateJLabel.setText("Interest Rate (as %)");
        getContentPane().add(rateJLabel);

        rateJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rateJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rateJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rateJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(rateJTextField);

        yearsJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearsJLabel.setText("Years");
        getContentPane().add(yearsJLabel);

        yearsJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yearsJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yearsJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(yearsJTextField);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void counterJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_counterJTextFieldActionPerformed
    {//GEN-HEADEREND:event_counterJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counterJTextFieldActionPerformed

    private void amountJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_amountJTextFieldActionPerformed
    {//GEN-HEADEREND:event_amountJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountJTextFieldActionPerformed

    private void rateJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rateJTextFieldActionPerformed
    {//GEN-HEADEREND:event_rateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateJTextFieldActionPerformed

    private void yearsJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yearsJTextFieldActionPerformed
    {//GEN-HEADEREND:event_yearsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LoanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JTextField amountJTextField;
    private javax.swing.JLabel counterJLabel;
    private javax.swing.JTextField counterJTextField;
    private javax.swing.JLabel rateJLabel;
    private javax.swing.JTextField rateJTextField;
    private javax.swing.JLabel yearsJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
}
