package Lab2;

import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * Class LoanGui File LoanGui.java Description Calculate loan payment given
 * amount, interest rate, and length
 *
 * @author Kevin Manning Environment PC, Windows 10, jdk8.2, NetBeans 8.1
 * @version 1.0
 * @see javax.swing.JFrame History Log 1/12 - Created Project; added GUI and
 * starting codes
 */
public class LoanGUI extends javax.swing.JFrame
{

    /**
     * Creates new form LoanGUI
     */
    public LoanGUI()
    {
        initComponents();
        //set Calculate button as default
        this.getRootPane().setDefaultButton(calculateJButton);
        //center window
        this.setLocationRelativeTo(null);
        //set icon for the form
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Lab2/img0.jpg"));
        amountJTextField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        counterJLabel = new javax.swing.JLabel();
        counterJTextField = new javax.swing.JTextField();
        amountJLabel = new javax.swing.JLabel();
        amountJTextField = new javax.swing.JTextField();
        rateJLabel = new javax.swing.JLabel();
        rateJTextField = new javax.swing.JTextField();
        yearsJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();
        calculateJButton = new javax.swing.JButton();
        paymentJTextField = new javax.swing.JTextField();
        interestJLabel = new javax.swing.JLabel();
        interestJTextField = new javax.swing.JTextField();
        clearJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 5, 5));

        counterJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        counterJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        counterJLabel.setText("Calculation Counter");
        getContentPane().add(counterJLabel);

        counterJTextField.setEditable(false);
        counterJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        counterJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        counterJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                counterJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(counterJTextField);

        amountJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amountJLabel.setText("Loan Amount");
        getContentPane().add(amountJLabel);

        amountJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amountJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                amountJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(amountJTextField);

        rateJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rateJLabel.setText("Interest Rate (as %)");
        getContentPane().add(rateJLabel);

        rateJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rateJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rateJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rateJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(rateJTextField);

        yearsJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearsJLabel.setText("Years");
        getContentPane().add(yearsJLabel);

        yearsJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yearsJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yearsJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(yearsJTextField);

        calculateJButton.setBackground(new java.awt.Color(153, 153, 255));
        calculateJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate Payment");
        calculateJButton.setToolTipText("Calculate Loan Payment");
        calculateJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                calculateJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateJButton);

        paymentJTextField.setEditable(false);
        paymentJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paymentJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paymentJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                paymentJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(paymentJTextField);

        interestJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        interestJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        interestJLabel.setText("Interest Paid");
        getContentPane().add(interestJLabel);

        interestJTextField.setEditable(false);
        interestJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        interestJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        interestJTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                interestJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(interestJTextField);

        clearJButton.setBackground(new java.awt.Color(153, 153, 255));
        clearJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearJButton.setMnemonic('L');
        clearJButton.setText("Clear");
        clearJButton.setToolTipText("Reset Calculator");
        clearJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearJButton);

        quitJButton.setBackground(new java.awt.Color(153, 153, 255));
        quitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quitJButton.setMnemonic('X');
        quitJButton.setText("Exit");
        quitJButton.setToolTipText("Exit Program");
        quitJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitJButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void counterJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_counterJTextFieldActionPerformed
    {//GEN-HEADEREND:event_counterJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counterJTextFieldActionPerformed

    private void amountJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_amountJTextFieldActionPerformed
    {//GEN-HEADEREND:event_amountJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountJTextFieldActionPerformed

    private void rateJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rateJTextFieldActionPerformed
    {//GEN-HEADEREND:event_rateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateJTextFieldActionPerformed

    private void yearsJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yearsJTextFieldActionPerformed
    {//GEN-HEADEREND:event_yearsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsJTextFieldActionPerformed

    private void paymentJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_paymentJTextFieldActionPerformed
    {//GEN-HEADEREND:event_paymentJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentJTextFieldActionPerformed

    private void interestJTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_interestJTextFieldActionPerformed
    {//GEN-HEADEREND:event_interestJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestJTextFieldActionPerformed

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitJButtonActionPerformed
    {//GEN-HEADEREND:event_quitJButtonActionPerformed
        // End applicaiton
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed
    int counter = 0;
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculateJButtonActionPerformed
    {//GEN-HEADEREND:event_calculateJButtonActionPerformed
        try
        {
// Calculate the Loan Payment
            //Declare variables & assign
            final int months = 12, percentConverter = 100;

            DecimalFormat twoDecimal = new DecimalFormat("$#,##0.00");

            double loanAmount = Double.parseDouble(amountJTextField.getText());
            double rate = Double.parseDouble(rateJTextField.getText()) / percentConverter;
            double years = Double.parseDouble(yearsJTextField.getText());

            double payment = 0f;
            double interest = 0f;
            boolean invalidInputs = (loanAmount <= 0 || loanAmount > 1000000000 || rate < 0 || rate > 100 || years < 0 || years > 100);
            
            if(invalidInputs)
                throw new NumberFormatException();
            
            //Input
            //Processing
            double top = 0.0, bottom = 0.0, monthlyInterestRate = rate / months;
            top = loanAmount * monthlyInterestRate;
            bottom = 1 - Math.pow((1 + monthlyInterestRate), (years * -months));

            payment = top / bottom;
            interest = payment * months * years - loanAmount;
            counter++;

            //Output
            counterJTextField.setText(String.valueOf(counter));
            paymentJTextField.setText(twoDecimal.format(payment));
            interestJTextField.setText(twoDecimal.format(interest));
        } catch (NumberFormatException exp)
        {
            JOptionPane.showMessageDialog(null, "Please enter a positive number for all required fields", "Input Error", JOptionPane.ERROR_MESSAGE);

            amountJTextField.requestFocus();
            amountJTextField.selectAll();
        }


    }//GEN-LAST:event_calculateJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearJButtonActionPerformed
    {//GEN-HEADEREND:event_clearJButtonActionPerformed
        // Clear All Fields and Reset Form
        amountJTextField.setText("");
        counterJTextField.setText("");
        rateJTextField.setText("");
        yearsJTextField.setText("");
        paymentJTextField.setText("");
        interestJTextField.setText("");
        amountJTextField.requestFocus();
    }//GEN-LAST:event_clearJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LoanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JTextField amountJTextField;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JLabel counterJLabel;
    private javax.swing.JTextField counterJTextField;
    private javax.swing.JLabel interestJLabel;
    private javax.swing.JTextField interestJTextField;
    private javax.swing.JTextField paymentJTextField;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel rateJLabel;
    private javax.swing.JTextField rateJTextField;
    private javax.swing.JLabel yearsJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
}
